# Generated by Django 4.2.1 on 2023-05-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('probeg', models.CharField(max_length=50)),
                ('power', models.CharField(max_length=50)),
                ('obiem', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('opisanie', models.CharField(max_length=500)),
                ('hozyain', models.CharField(max_length=50)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
