# Generated by Django 4.2.1 on 2023-05-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cars',
            name='hozyain',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cars',
            name='img',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cars',
            name='obiem',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cars',
            name='opisanie',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='cars',
            name='power',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cars',
            name='probeg',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.CharField(max_length=300),
        ),
    ]
