# Generated by Django 4.2.1 on 2023-06-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_color_alter_cars_hozyain_alter_cars_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('anons', models.CharField(max_length=1000)),
                ('full', models.CharField(max_length=10000)),
                ('img', models.CharField(max_length=1000)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='callNumber',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
